name: 'validate package-lock.json '
description: 'this action will bump version of npm based library/package. it will work against the aws codeartifact registry and not against the package.json'
inputs:
  registry:
    description: "the account id in which the CodeArtifact is located"
    required: true
    type: string
    default: 974360507615
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: ./validate.lock.file.sh ${{ inputs.registry }}
      shell: bash
